name = "crazy-weapon-man"
compatibility_date = "2026-09-13"
pages_build_output_dir = "public"

# Configure the production D1 binding in Cloudflare Pages:
# Settings -> Bindings -> D1 database -> variable name: DB
